include:
- local: templates/renovate.yaml
- local: templates/docker.yaml
- local: templates/ubuntu.yaml
- local: templates/build-essential.yaml
- local: templates/alpine.yaml
- local: templates/wolfi.yaml
