.docker-login:
  before_script:
  - |
    echo "${CI_REGISTRY_PASSWORD}" \
    | docker login "${CI_REGISTRY}" \
        --username "${CI_REGISTRY_USER}" \
        --password-stdin

ubuntu-build:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    changes:
    - ubuntu/Dockerfile
    variables:
      PUSH: "true"
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    changes:
    - ubuntu/Dockerfile
    variables:
      PUSH: "false"
  - if: $CI_PIPELINE_SOURCE == "web"
    variables:
      PUSH: "true"
  parallel:
    matrix:
    - VERSION:
      - "24.04"
      - "rolling"
      ARCH:
      - "amd64"
      - "arm64"
  services:
  - docker:27.3.1-dind
  extends:
  - .docker-login
  image: docker:27.3.1
  variables:
    IMAGE_NAME: ubuntu
    BUILD_CONTEXT: ubuntu
  script:
  - |
    SOURCE_DATE_EPOCH="$( git log -1 --pretty=%ct "${IMAGE_NAME}/Dockerfile" )"
    export SOURCE_DATE_EPOCH
  - |
    docker buildx build "${BUILD_CONTEXT}" \
        --build-arg=VERSION \
        --cache-to=type=inline,mode=min \
        --cache-from=type=registry,ref="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${VERSION}-${ARCH}" \
        --tag="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${VERSION}-${ARCH}" \
        --push="${PUSH}"
  tags:
  - saas-linux-medium-${ARCH}

ubuntu-index:
  needs:
  - ubuntu-build
  parallel:
    matrix:
    - VERSION:
      - "24.04"
      - "rolling"
  extends:
  - .docker-login
  image: docker:27.3.1
  variables:
    IMAGE_NAME: ubuntu
  script:
  - |
    docker buildx imagetools create --tag "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${VERSION}" \
        "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${VERSION}-amd64" \
        "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${VERSION}-arm64"