.docker-login:
  before_script:
  - |
    echo "${CI_REGISTRY_PASSWORD}" \
    | docker login "${CI_REGISTRY}" \
        --username "${CI_REGISTRY_USER}" \
        --password-stdin

ubuntu-build:
  parallel:
    matrix:
    - VERSION:
      - "24.04"
      - "rolling"
      ARCH:
      - "amd64"
      - "arm64"
  services:
  - docker:27.3.1-dind
  extends:
  - .docker-login
  image: docker:27.3.1
  script:
  - |
    SOURCE_DATE_EPOCH="$(git log -1 --pretty=%ct ubuntu/Dockerfile)"
    export SOURCE_DATE_EPOCH
  - |
    docker buildx build ubuntu \
        --build-arg=VERSION \
        --cache-to=type=inline,mode=min \
        --cache-from=type=registry,ref="${CI_REGISTRY_IMAGE}/ubuntu:${VERSION}-${ARCH}" \
        --tag="${CI_REGISTRY_IMAGE}/ubuntu:${VERSION}-${ARCH}" \
        --push
  tags:
  - saas-linux-medium-${ARCH}

ubuntu-index:
  needs:
  - ubuntu-build
  parallel:
    matrix:
    - VERSION:
      - "24.04"
      - "rolling"
  extends:
  - .docker-login
  image: docker:27.3.1
  script:
  - |
    docker buildx imagetools create --tag "${CI_REGISTRY_IMAGE}/ubuntu:${VERSION}" \
        "${CI_REGISTRY_IMAGE}/ubuntu:${VERSION}-amd64" \
        "${CI_REGISTRY_IMAGE}/ubuntu:${VERSION}-arm64"