include:
- local: templates/docker.yaml
- local: templates/ubuntu.yaml
- local: templates/build-essential.yaml
- local: templates/alpine.yaml
- local: templates/build-base.yaml
- local: templates/wolfi.yaml
- local: templates/systemd.yaml
- project: uniget-org/templates
  file: renovate.yaml
  ref: main